# Generated by Django 5.1.6 on 2025-04-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0005_alter_major_major_name_alter_university_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='department',
            field=models.CharField(choices=[('Business and Economics', 'Business and Economics'), ('Education', 'Education'), ('Engineering and Technology', 'Engineering and Technology'), ('Arts and Design', 'Arts and Design'), ('Agriculture and Environmental Studies', 'Agriculture and Environmental Studies'), ('Communication and Media', 'Communication and Media'), ('Law and Criminal Justice', 'Law and Criminal Justice')], db_index=True, max_length=50),
        ),
    ]
