# Generated by Django 5.1.6 on 2025-04-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0006_alter_major_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='savedCalcs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
